/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-03-28 05:55:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class aboutme_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1651733799535L));
    _jspx_dependants.put("jar:file:/D:/Tai%20lieu%20hoc%20ki%202%20nam%203/CSDL_NC/git/DUAN_NHOM3_CSDLNC/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebChiaSeHinhAnh/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"icon\" href=\"img/Logo.png\" type=\"image/x-icon\">\r\n");
      out.write("<title>PIXEL</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\"\r\n");
      out.write("	content=\"Mark Otto, Jacob Thornton, and Bootstrap contributors\">\r\n");
      out.write("<meta name=\"generator\" content=\"Hugo 0.104.2\">\r\n");
      out.write("<link rel=\"canonical\"\r\n");
      out.write("	href=\"https://getbootstrap.com/docs/5.2/examples/album/\">\r\n");
      out.write("<link rel=\"canonical\"\r\n");
      out.write("	href=\"https://getbootstrap.com/docs/5.2/examples/headers/\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css\">\r\n");
      out.write("<link href=\"assets/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/aboutme.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/modal.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "headers.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<!-- Thông tin người dùng -->\r\n");
      out.write("	<section class=\"text-center container\"\r\n");
      out.write("		style=\"padding: 30px 100px 5px 100px; z-index: 1\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"album bg-light\"\r\n");
      out.write("				style=\"border-radius: 15px 15px 0 0; padding-bottom: 20px;\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<div class=\"col-lg\"\r\n");
      out.write("						style=\"display: flex; align-content: row; padding: 15px 0 30px 0\">\r\n");
      out.write("						<img class=\"bd-placeholder-img rounded-circle\"\r\n");
      out.write("							src=\"img/userimage/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${AC.uImages}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" width=\"160\" height=\"160\"\r\n");
      out.write("							role=\"img\" aria-label=\"Placeholder: 140x140\">\r\n");
      out.write("						<div\r\n");
      out.write("							style=\"display: flex; flex-direction: column; align-items: flex-start; margin-left: 20px; margin-top: 10px; line-height: 0.1;\">\r\n");
      out.write("							<h1 class=\"text-nowrap\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${AC.lastName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${AC.firstName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1>\r\n");
      out.write("\r\n");
      out.write("							<p class=\"bi bi-envelope-fill\">\r\n");
      out.write("								<a\r\n");
      out.write("									style=\"text-decoration: none; font-weight: bold; font-size: 14px\"\r\n");
      out.write("									href=\"#\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc.gmail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\r\n");
      out.write("							</p>\r\n");
      out.write("							<p class=\"bi bi-facebook\">\r\n");
      out.write("								<a target=\"_blank\"\r\n");
      out.write("									style=\"text-decoration: none; font-weight: bold; font-size: 14px\"\r\n");
      out.write("									href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc.faceBook}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("									");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc.faceBook}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\r\n");
      out.write("							</p>\r\n");
      out.write("							<p class=\"bi bi-telephone-fill\">\r\n");
      out.write("								<a\r\n");
      out.write("									style=\"text-decoration: none; font-weight: bold; font-size: 14px\"\r\n");
      out.write("									href=\"#\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc.soDienThoai}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\r\n");
      out.write("							</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div\r\n");
      out.write("						style=\"display: flex; justify-content: flex-end; position: relative; bottom: 20px;\">\r\n");
      out.write("						<div style=\"margin-right: 27px\">\r\n");
      out.write("							<a href=\"#editInf\" type=\"button\" class=\"btn btn-outline-primary\">Chỉnh\r\n");
      out.write("								sửa thông tin cá nhân</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<a href=\"#upload\" type=\"button\" class=\"btn btn-primary\">Tải\r\n");
      out.write("								ảnh lên</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<!-- gallery -->\r\n");
      out.write("	<section class=\"text-center container\"\r\n");
      out.write("		style=\"padding: 0 100px 50px 100px; z-index: 1\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"album bg-light\"\r\n");
      out.write("				style=\"border-radius: 0 0 15px 15px; padding-bottom: 20px;\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<!-- /.col-lg-4 -->\r\n");
      out.write("					<div class=\"row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3\">\r\n");
      out.write("						");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<div class=\"modal\" id=\"upload\">\r\n");
      out.write("		<div class=\"modal__overlay\"></div>\r\n");
      out.write("		<div class=\"modal__body\">\r\n");
      out.write("			<form action=UpLoadControl method=\"post\"\r\n");
      out.write("				enctype=\"multipart/form-data\" class=\" row g-3\r\n");
      out.write("				m-auto\"\r\n");
      out.write("				style=\"width: 40%; padding: 15px; z-index: 2; background-color: #f8f9fa; border-radius: 10px\">\r\n");
      out.write("				<a style=\"display: flex; justify-content: flex-end; margin: 0\"\r\n");
      out.write("					href=\"#\"><i class=\"bi bi-x-lg\"></i></a>\r\n");
      out.write("				<h1 class=\"h3 mb-3 fw-normal m-auto text-center\">Upload Image</h1>\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<input name=\"imgUpload\" type=\"file\" class=\"form-control\"\r\n");
      out.write("						placeholder=\"Link hình ảnh\"  required accept=\"image/*\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<input name=\"tieucu\" type=\"text\" class=\"form-control\"\r\n");
      out.write("						id=\"inputEmail4\" placeholder=\"Tiêu cự(VD:50,70,24,....)\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<input name=\"khaudo\" type=\"text\" class=\"form-control\"\r\n");
      out.write("						id=\"inputEmail4\" placeholder=\"Khẩu độ(VD:f1.8, f/2.5,...)\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<input name=\"tocdomantrap\" type=\"text\" class=\"form-control\"\r\n");
      out.write("						id=\"inputEmail4\" placeholder=\"Tốc độ màn trập(VD:1/200s,...)\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<input name=\"iso\" type=\"text\" class=\"form-control\" id=\"inputEmail4\"\r\n");
      out.write("						placeholder=\"ISO(VD:1000)\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<input name=\"tenmayanh\" type=\"text\" class=\"form-control\"\r\n");
      out.write("						id=\"inputEmail4\" placeholder=\"Tên máy ảnh\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<select name=\"loaihinh\" class=\"form-select\"\r\n");
      out.write("						aria-label=\"Default select example\" required>\r\n");
      out.write("						<option value=\"\" selected disabled>Loại hình ảnh</option>\r\n");
      out.write("						<option value=\"PNG\">PNG</option>\r\n");
      out.write("						<option value=\"JPG\">JPG</option>\r\n");
      out.write("						<option value=\"GIF\">GIF</option>\r\n");
      out.write("					</select>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<input name=\"tag\" type=\"text\" class=\"form-control\" id=\"inputEmail4\"\r\n");
      out.write("						placeholder=\"Tag(VD:Con người, Động vật, cây cối,...)\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<select name=\"cate_id\" class=\"form-select\"\r\n");
      out.write("						aria-label=\"Default select example\" required>\r\n");
      out.write("						<option value=\"\" selected disabled>Chọn danh mục</option>\r\n");
      out.write("						");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					</select>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<select name=\"isPublic\" class=\"form-select\"\r\n");
      out.write("						aria-label=\"Default select example\" required>\r\n");
      out.write("						<option value=\"Công khai\">Công khai</option>\r\n");
      out.write("						<option value=\"Chỉ mình tôi\">Chỉ mình tôi</option>\r\n");
      out.write("					</select>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12\"\r\n");
      out.write("					style=\"display: flex; justify-content: flex-end;\">\r\n");
      out.write("					<button type=\"submit\" value=\"Register\" class=\"btn btn-primary\">UPLOAD</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("			<div class=\"moda__inner\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!--end UpLoad -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--Edit img-->\r\n");
      out.write("	<div class=\"modal\" id=\"edit\">\r\n");
      out.write("		<div class=\"modal__overlay\"></div>\r\n");
      out.write("		<div class=\"modal__body\">\r\n");
      out.write("			<form action=\"EditImgControl\" method=\"post\" class=\"row g-3 m-auto\"\r\n");
      out.write("				style=\"width: 40%; padding: 15px; z-index: 2; background-color: #f8f9fa; border-radius: 10px\">\r\n");
      out.write("				<a style=\"display: flex; justify-content: flex-end; margin: 0\"\r\n");
      out.write("					href=\"#\"><i class=\"bi bi-x-lg\"></i></a>\r\n");
      out.write("				<h1 class=\"h3 mb-3 fw-normal m-auto text-center\">EDIT IMAGES</h1>\r\n");
      out.write("				<div\r\n");
      out.write("					style=\"padding-top: 20px; display: flex; justify-content: center;\">\r\n");
      out.write("					<img src=\"img/dataImg/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.images}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("						style=\"max-width: 100%; height: 50vh;\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.idImage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"idImage\" readonly\r\n");
      out.write("						type=\"text\" class=\"form-control\" id=\"inputEmail4\"\r\n");
      out.write("						placeholder=\"Tiêu cự(VD:50,70,24,....)\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.tieuCu}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"tieucu\" type=\"text\"\r\n");
      out.write("						class=\"form-control\" id=\"inputEmail4\"\r\n");
      out.write("						placeholder=\"Tiêu cự(VD:50,70,24,....)\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.khauDo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"khaudo\" type=\"text\"\r\n");
      out.write("						class=\"form-control\" id=\"inputEmail4\"\r\n");
      out.write("						placeholder=\"Khẩu độ(VD:f1.8, f/2.5,...)\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.tocDoManTrap}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"tocdomantrap\"\r\n");
      out.write("						type=\"text\" class=\"form-control\" id=\"inputEmail4\"\r\n");
      out.write("						placeholder=\"Tốc độ màn trập(VD:1/200s,...)\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.iSO}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"iso\" type=\"text\"\r\n");
      out.write("						class=\"form-control\" id=\"inputEmail4\" placeholder=\"ISO(VD:1000)\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.camera}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"tenmayanh\" type=\"text\"\r\n");
      out.write("						class=\"form-control\" id=\"inputEmail4\" placeholder=\"Tên máy ảnh\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<select name=\"loaihinh\" class=\"form-select\"\r\n");
      out.write("						aria-label=\"Default select example\">\r\n");
      out.write("						<option selected>Loại hình ảnh</option>\r\n");
      out.write("						<option value=\"PNG\">PNG</option>\r\n");
      out.write("						<option value=\"JPG\">JPG</option>\r\n");
      out.write("						<option value=\"GIF\">GIF</option>\r\n");
      out.write("					</select>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${detail.tag}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"tag\" type=\"text\"\r\n");
      out.write("						class=\"form-control\" id=\"inputEmail4\"\r\n");
      out.write("						placeholder=\"Tag(VD:Con người, Động vật, cây cối,...)\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<select name=\"cate_id\" class=\"form-select\"\r\n");
      out.write("						aria-label=\"Default select example\">\r\n");
      out.write("						<option selected>Chọn danh mục</option>\r\n");
      out.write("						");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					</select>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12\"\r\n");
      out.write("					style=\"display: flex; justify-content: flex-end;\">\r\n");
      out.write("					<button type=\"submit\" class=\"btn btn-primary\">UPLOAD</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("			<div class=\"moda__inner\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Đổi inf -->\r\n");
      out.write("	<div class=\"modal\" id=\"editInf\">\r\n");
      out.write("		<div class=\"modal__overlay\"></div>\r\n");
      out.write("		<div class=\"modal__body\">\r\n");
      out.write("			<form action=\"EditInfUserControl\" method=\"post\"\r\n");
      out.write("				enctype=\"multipart/form-data\" class=\"row g-3 m-auto\"\r\n");
      out.write("				style=\"width: 50%; padding: 15px; z-index: 2; background-color: #f8f9fa; border-radius: 10px\">\r\n");
      out.write("				<a style=\"display: flex; justify-content: flex-end; margin: 0\"\r\n");
      out.write("					href=\"#\"><i class=\"bi bi-x-lg\"></i></a>\r\n");
      out.write("				<div style=\"display: flex;\">\r\n");
      out.write("					");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<input name=\"imgUserUpload\" type=\"file\" class=\"form-control\">\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					\r\n");
      out.write("						<input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${AC.gmail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"email\" type=\"email\" class=\"form-control\" id=\"inputEmail4\" placeholder=\"Email\" required>\r\n");
      out.write("						\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-6\">\r\n");
      out.write("					\r\n");
      out.write("						<input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${AC.password}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"pass\" type=\"password\" class=\"form-control\" id=\"inputPassword4\" placeholder=\"Mật khẩu\" required>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-6\">\r\n");
      out.write("					<input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${AC.password}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"repeatpassword\" type=\"password\"\r\n");
      out.write("						class=\"form-control\" id=\"inputPassword4\" placeholder=\"Xác nhận\" required>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${AC.firstName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"firstName\" type=\"text\"\r\n");
      out.write("						class=\"form-control\" id=\"inputAddress\" placeholder=\"firstName\" required >\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${AC.lastName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"lastName\" type=\"text\"\r\n");
      out.write("						class=\"form-control\" id=\"inputAddress\" placeholder=\"lastName\" required >\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<select name=\"gender\" class=\"form-select\"\r\n");
      out.write("						aria-label=\"Default select example\">\r\n");
      out.write("						<option selected>Giới tính</option>\r\n");
      out.write("						<option value=\"Nam\">Nam</option>\r\n");
      out.write("						<option value=\"Nữ\">Nữ</option>\r\n");
      out.write("					</select>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${AC.faceBook}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"faceBook\" type=\"text\"\r\n");
      out.write("						class=\"form-control\" id=\"inputAddress\" placeholder=\"Link FaceBook\" required >\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${AC.soDienThoai}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"soDienThoai\" type=\"text\"\r\n");
      out.write("						class=\"form-control\" id=\"inputAddress\" placeholder=\"Số điện thoại\" required >\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12\">\r\n");
      out.write("					<button class=\"w-100 btn btn-lg btn-primary\" type=\"submit\">Xong</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("			<div class=\"moda__inner\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!--xem hình-->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /aboutme.jsp(88,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/aboutme.jsp(88,6) '${listUID}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listUID}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /aboutme.jsp(88,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("UID");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("							<div style=\"columns: 3 250px; gap: 10px;\">\r\n");
            out.write("								");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("								");
            if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("							</div>\r\n");
            out.write("						");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /aboutme.jsp(90,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UID.ready==0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									<div class=\"dropdown text-end\"\r\n");
          out.write("										style=\"display: flex; justify-content: flex-end; position: relative; top: 44px; right: 10px; z-index: 2\">\r\n");
          out.write("										<a\r\n");
          out.write("											style=\"align-items: center; background-color: #f8f9fac4; border-radius: 50%; font-size: 12px; justify-content: center; padding: 9px 12px; text-align: center;\"\r\n");
          out.write("											class=\"d-block link-dark text-decoration-none bi bi-pencil-square \"\r\n");
          out.write("											data-bs-toggle=\"dropdown\" aria-expanded=\"false\"> </a>\r\n");
          out.write("										<ul class=\"dropdown-menu text-small\"\r\n");
          out.write("											style=\"position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate3d(112.4px, 38.4px, 0px);\">\r\n");
          out.write("											<li><a class=\"dropdown-item \" style=\"\"\r\n");
          out.write("												href=\"DeleteControl?Iid=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UID.idImage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">Xoá</a></li>\r\n");
          out.write("											<li><a class=\"dropdown-item\"\r\n");
          out.write("												href=\"AboutControl?Iid=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UID.idImage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("#edit\">Sửa</a></li>\r\n");
          out.write("										</ul>\r\n");
          out.write("									</div>\r\n");
          out.write("						\r\n");
          out.write("									<img\r\n");
          out.write("										style=\"border-radius: 5px; opacity: 0.5; position: relative; z-index: 1\"\r\n");
          out.write("										class=\"bd-placeholder-img card-img-top\" width=\"100%\"\r\n");
          out.write("										height=\"225vh\" src=\"img/dataImg/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UID.images}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /aboutme.jsp(111,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UID.ready==1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("									<div class=\"dropdown text-end\"\r\n");
          out.write("										style=\"display: flex; justify-content: flex-end; position: relative; top: 44px; right: 10px;\">\r\n");
          out.write("										<a\r\n");
          out.write("											style=\"align-items: center; background-color: #f8f9fac4; border-radius: 50%; font-size: 12px; justify-content: center; padding: 9px 12px; text-align: center;\"\r\n");
          out.write("											class=\"d-block link-dark text-decoration-none bi bi-pencil-square \"\r\n");
          out.write("											data-bs-toggle=\"dropdown\" aria-expanded=\"false\"> </a>\r\n");
          out.write("										<ul class=\"dropdown-menu text-small\"\r\n");
          out.write("											style=\"position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate3d(112.4px, 38.4px, 0px);\">\r\n");
          out.write("											<li><a class=\"dropdown-item \" style=\"\"\r\n");
          out.write("												href=\"DeleteControl?Iid=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UID.idImage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">Xoá</a></li>\r\n");
          out.write("											<li><a class=\"dropdown-item\"\r\n");
          out.write("												href=\"AboutControl?Iid=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UID.idImage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("#edit\">Sửa</a></li>\r\n");
          out.write("										</ul>\r\n");
          out.write("									</div>\r\n");
          out.write("									<a\r\n");
          out.write("							href=\"ImageDetail?Iid=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UID.idImage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&Uid=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UID.userID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&Cid=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UID.idCategory}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("									<img style=\"border-radius: 5px;\"\r\n");
          out.write("										class=\"bd-placeholder-img card-img-top\" width=\"100%\"\r\n");
          out.write("										height=\"225vh\" src=\"img/dataImg/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${UID.images}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"></a>\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /aboutme.jsp(196,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/aboutme.jsp(196,6) '${listC}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listC}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /aboutme.jsp(196,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("C");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("							<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${C.idCategory}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${C.cname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("						");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /aboutme.jsp(286,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/aboutme.jsp(286,6) '${listC}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listC}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /aboutme.jsp(286,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("C");
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("							<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${C.idCategory}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${C.cname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("						");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /aboutme.jsp(309,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc.uImages != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<img class=\"bd-placeholder-img rounded-circle\"\r\n");
          out.write("							src=\"img/userimage/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${AC.uImages}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" width=\"140\" height=\"140\"\r\n");
          out.write("							role=\"img\" aria-label=\"Placeholder: 140x140\"\r\n");
          out.write("							style=\"margin: auto;\">\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /aboutme.jsp(315,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc.uImages == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<img class=\"bd-placeholder-img rounded-circle\"\r\n");
          out.write("							src=\"https://cdn-icons-png.flaticon.com/512/1946/1946429.png\"\r\n");
          out.write("							width=\"140\" height=\"140\" role=\"img\"\r\n");
          out.write("							aria-label=\"Placeholder: 140x140\" style=\"margin: auto;\">\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }
}
